  services:
    cassandra:
      image: cassandra:5.0
      container_name: cassandraSol
      ports:
        - "9042:9042"
      networks:
        - cassandra-networks
  networks:
    cassandra-networks:
      driver: bridge